### ISSUE TITLE
Estruturas de dados e comunicação com APIs

### ISSUE THREAD

**Issue by rafaelcanovas** [caueamaral/anima-vita#1]
https://github.com/caueamaral/anima-vita/blob/bc1863b76d977426351aa3413b700ff67e5a3e1c/src/components/Card/index.js#L11-L21

Bom dia Cauê!

Para uma aplicação pequena, chamar a API direto no componente é algo que funciona, no entanto, com o crescimento da aplicação encontramos novos desafios. Múltiplas partes da aplicação precisam chamar a mesma API, aparece a necessidade da criação de estruturas de dados, com tipagem, para que os dados vindos de fontes externas não interfiram na estabilidade da aplicação e sejam muito mais fáceis de dar manutenção.

Como você enxergaria essa evolução dentro de uma aplicação como esta?

**Comment by caueamaral** [comment]
Oi Rafael.

Realmente, com o crescimento da aplicação não seria uma boa prática deixar tudo no mesmo arquivo. Quanto maior o projeto é, ou se torna, maior a necessidade de desacoplamento de código.

Basicamente eu extrairia as constantes "apiUrl", "apiHeaders" e a função do "axios.get()" e deixaria tudo em uma função que ficaria em um arquivo isolado. Esse função poderia se chamar algo como "getCards()" que poderia ser reutilizada em outras partes da aplicação.

A respeito da tipagem, basicamente eu poderia utilizar o TypeScript para garantir que o retorno dessa função seja sempre um array. Já que o setCards() foi projetado para receber um array. Sendo assim diminuiriam as chances de o código quebrar quando a API não respondesse.

**Comment by rafaelcanovas** [comment]
Obrigado!
