### ISSUE TITLE
Testes unitários

### ISSUE THREAD

**Issue by rafaelcanovas** [caueamaral/anima-vita#2]
Bom dia Cauê!

Vi que você configurou a suíte de testes unitários mas acabou utilizando somente pra testar o `App`.

Qual técnica você utilizaria para escrever um teste para o componente `Card`, que realiza uma chamada para API e renderiza de acordo com o resultado? 
https://github.com/caueamaral/anima-vita/blob/bc1863b76d977426351aa3413b700ff67e5a3e1c/src/App.test.js#L4-L8

**Comment by caueamaral** [comment]
Para ser sincero, eu não cheguei a configurar a suíte de testes, basicamente por eu ter utilizado o "create-react-app" essa estrutura já foi criada para mim automaticamente, eu apenas conferi se ela por si só gerava algum tipo de bug, e como não gerou não vi problema eu deixa-lá pre-configurada para uma posterior necessidade.

Agora realmente respondendo a pergunta eu faria um teste unitário da função "getCards()", faria basicamente um Mock de um array de objetos simplificado com as informações que a API retorna. E principalmente me preocuparia ainda mais com o tratamento de erro da função em caso de API não responder. Para por exemplo sempre retornar um array, nem que ele seja vazio, já que quem utilizar a função "getCards" provavelmente vai utilizar métodos de array com o ".map" para percorre-lo.

Apesar de isso acabar permitindo que alguém percorra um array vazio, o que não é nada performático, ao menos não quebra a aplicação em tempo de execução.

**Comment by rafaelcanovas** [comment]
Obrigado!
