### ISSUE TITLE
Props e contexto

### ISSUE THREAD

**Issue by rafaelcanovas** [caueamaral/anima-vita#3]
Bom dia Cauê!

Percebi que para indicar o carregamento da aplicação você criou uma variável de estado na aplicação e passou a função que muta ela por props para os componentes filhos. Acredito que para uma aplicação de pequeno/médio porte isso funciona *muito* bem! O redux aqui seria usar uma espingarda pra matar uma formiga.

No entanto com o crescimento da aplicação, como você enxerga a manutenção dessas props e variáveis "globais" da aplicação? Qual é sua técnica preferida pra resolver esse problema? 

https://github.com/caueamaral/anima-vita/blob/bc1863b76d977426351aa3413b700ff67e5a3e1c/src/App.js#L23

**Comment by caueamaral** [comment]
Sendo sincero até o momento não tive a oportunidade de trabalhar com "React" em um projeto grande e sentir na prática esse problema, porém estou ciente que ficar atualizando o estado da aplicação a todo momento não é nada performático.

A curva de aprendizado do Redux não me pareceu muito simples. Provavelmente eu utilizaria a "Context API" para resolver esse problema das variáveis globais, justamente para não precisar ficar passando para os componentes filhos manualmente.

A respeito de usar uma espingarda para matar uma formiga, realmente, eu não tenho o costume de programar adicionando tecnologias sem necessidade.

**Comment by rafaelcanovas** [comment]
Obrigado!

**Comment by mstrcnvs** [comment]
Obrigado!
